#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PadillaMelitonAssn3.Resource", IsApplication=true)]

namespace PadillaMelitonAssn3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int my_blue = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int my_gray = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int my_green = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int my_purple = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int layout_background = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int btnFifthActivity = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int btnFourthActivity = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int btnGetData = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int btnSecondActivity = 2131165189;
			
			// aapt resource value: 0x7f07000c
			public const int btnTestConnection = 2131165196;
			
			// aapt resource value: 0x7f070006
			public const int btnThirdActivity = 2131165190;
			
			// aapt resource value: 0x7f07000d
			public const int cbInternetConnection = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int radioEthernet = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int radioMobileData = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int radioWiFi = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int radioWiMax = 2131165201;
			
			// aapt resource value: 0x7f070004
			public const int tableLayout1 = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int tvMANUFACTURERData = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int tvMODELData = 2131165185;
			
			// aapt resource value: 0x7f070009
			public const int tvOrientationData = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int tvPRODUCTData = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int tvScreenHeightData = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int tvScreenWidthData = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FifthLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FourthLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SecondLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ThirdLayout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyCustomTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
